version: "3.9"
services:
  server:
    build:
      context: .
      target: server
    ports:
      - "3000:3000"
  client:
    build:
      context: .
      target: client
    ports:
      - "5173:80"
    env_file:
      - ./.env
